#!/usr/bin/env bash

#colors
#bold="(tput bold)"
magenta="\033[1;35m"
green="\033[1;32m"
white="\033[1;37m"
blue="\033[1;34m"
red="\033[1;31m"
#black="(tput setaf 0)"
yellow="\033[1;33m"
cyan="\033[1;36m"
#c0="${reset}${bold}"
c1="${magenta}"
c2="${green}"
c3="${white}"
c4="${blue}"
c5="${red}"
c6="${yellow}"
c7="${cyan}"
#Get init name
pidof systemd && init="systemd" || init="$(cat /proc/1/comm)"
#get total packages

net_pkg() {
    pack="$(which {xbps-install,apk,apt,pacman,nix,yum,rpm,dpkg} 2>/dev/null | grep -v "not found" | awk -F/ 'NR==1{print $NF}')"
  case "${pack}" in
      "xbps-install")
	  total=$(xbps-query -l | wc -l)
	  ;;
      "apk")
	  total=$(apk search | wc -l)
	  ;;
      "apt")
	  total=$(apt list --installed 2>/dev/null | wc -l)
	  ;;
      "pacman")
	  total=$(pacman -Q | wc -l)
	  ;;
      "nix")
	  total=$(nix-env -qa --installed "*" | wc -l)
	  ;;
      "yum")
	  total=$(yum list installed | wc -l)
	  ;;
      "rpm")
	  total=$(rpm -qa | wc -l)
	  ;;
#      "dpkg")
#	  total=$(dpkg-query -l | wc -l)
#	  ;;
      "")
	  total="Unknown"
	  ;;
  esac

  echo $total
}

# check distro info for counting n.o of packages accordingly
distro_detect() {
    os="$(uname -o)"
    case "${os}" in
	Android)
	    distro="Android"
	    if [ ! -f "${HOME}"/.termux/fonts/Material.ttf ];then
		cp fonts/* "${HOME}"/.termux/fonts/
		termux-reload-settings
	    fi
	    ;;
	*)
	    distro="$(source /etc/os-release && echo "${PRETTY_NAME}")"
	    if [ ! -f /usr/share/fonts/Material.ttf ];then
		sudo cp fonts/* /usr/share/fonts/
		fc-cache -vf &>/dev/null
	    fi
	    ;;
    esac
}
# current memory usage and total ram
eq() { # <- credits to gk
  case $1 in
      $2)
      ;;
      *) return 1
	 ;;
  esac
}

while read -r line; do
  eq "$line" 'MemTotal*' && set -- $line && break
done </proc/meminfo
totalRam="$(($2 / 1000))"
mem="$(free -m | sed -n 's/^Mem:\s\+[0-9]\+\s\+\([0-9]\+\)\s.\+/\1/p')"
# fetch output
distro_detect
echo "               "
echo -e "               ${c1}os${c3}    ${distro} $(uname -m)"
echo -e "      .-.      ${c2}ker${c3}   $(uname -r)"
echo -e "      oo|      ${c7}pkgs${c3}  $(net_pkg)"
echo -e "     / '\      ${c4}sh${c3}    $(basename "${SHELL}")"
echo -e "    (\_;/)     ${c5}up${c3}   $(uptime -p | sed 's/up//')"
echo -e "               ${c6}ram${c3}   $mem / $totalRam MB"
echo -e "               ${c1}init${c4}    $init"
echo -e "               "
echo -e "     	 ${c6}󰮯 ${c6} ${c2}󰊠 ${c2} ${c4}󰊠 ${c4} ${c5}󰊠 ${c5} ${c7}󰊠 ${c7}"
echo -e "               \033[0m"
